---
name: "Letterboxd Watchlist"
guid: "b9bc9cff-1797-4a1e-bf8f-9ecdcf41f82a"
version: "0.0.2.0"
targetAbi: "10.11.6.0"
framework: "net9.0"
overview: "Sync Letterboxd watchlists to Jellyfin Collections"
description: >
  Create collections in Jellyfin that contain all the films found locally that appear in your Letterboxd watchlist.
category: "MoviesAndShows"
owner: "jellyfin"
artifacts:
- "LetterboxdWatchlist.dll"
- "HtmlAgilityPack.dll"
changelog: >
  changelog
